language: ruby
rvm:
  - 1.9.3
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
      - http://requestb.in/qqc3jiqq
    on_start: true