language: ruby
rvm:
  - 2.3.0
sudo: false
before_install:
  - cp config/application.example.yml config/application.yml
  - gem install bundler
before_script:
  - bundle exec rake db:migrate
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
cache: bundler
