language: ruby
rvm:
  - 2.0.0
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
notifications:
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true